name: Deploy on Push

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm run install:all

            - name: Start production server
              run: npm run start:prod
