name: Deploy on Push

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm run install:all

            - name: Stop existing Node.js processes
              run: |
                  pkill node || true
                  sleep 5  # Give time for processes to be killed
            - name: Delay before proceeding
              run: sleep 10 # Adjust the duration as needed

            - name: Start production server
              run: pm2 start 'npm run start:prod' - name 'JobApps'
