name: Deploy on Push

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  clean: false
            - name: Install dependencies
              run: npm run install:all

            - name: Build
              run: npm run build:all

            - name: Start production server
              run: pm2 start 'npm run deploy' --name 'JobApps'
